# Site settings
title: Nome del gruppo (Es. CoGiAr+)
description: Il nome del progetto (Kw. architettura, tecnologia, formazione)
owner: CoGiAr+ # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: # the subpath of your site, e.g. /blog
url: http://cogiar.github.io # the base hostname & protocol for your site
social:
  twitter: "#"
  #linkedin-square:
  #facebook-official:
  #google-plus-square:
  #email: /contact/
  flickr: "#"
  #instagram:
  # youtube-square: "#"
  vimeo: "#"
  github: "#"
  #soundcloud:
  #tumblr-square:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
